### ISSUE TITLE
Latest version (Jamais Vu) and other lenguajes

### ISSUE THREAD

**Issue by cualquiercosa327** [htmlbanjo/disco-courier#45]
Hi, thanks for the great stuff you have done.
I have bought on console and they are the latest version. 
I would love could use the data from them. 

Also could it be added external lenguages? 
I have extracted the translations (it is one big file, plus the fonts from
several lenguages as Russian) 

Thanks!

**Comment by htmlbanjo** [comment]
I'm don't _believe_ there should be any issue with additional languages, but let me know if you run into a problem.

As for the latest version (Jamais Vu), I haven't tested it yet, but you can disable any errors you get from the version check by editing the "migration.ts" file here:

https://github.com/htmlbanjo/disco-courier/blob/cb3317c636f198444d0b8a88d1518a3ba0e3a3c8/src/lib/migration.ts#L52

**Comment by cualquiercosa327** [comment]
Hi, I have edit this part, also on index.ts and it works.
Sadly I still have found some issues I can repair but others no, as

npm run courier  - -  - - export=md  - - start=4  - - results=1 conversations

Error on /src/search/actors.search.ts  :27
: getState('cache')?.actors.find(actor => actor[key] ==I'd)?. name

TypeError : Cannot read properties of undefined (reading 'find')

I have pm you on reddit
Thanks

**Comment by htmlbanjo** [comment]
Keeping the thread here to track the issue, and in case it helps others :]

Can you verify if you have the file  `/src/data/cache/actors.cache.json`? This should get created the first time it's run, to assist performance and normalize the list a bit.

**Comment by cualquiercosa327** [comment]
OK, it is late here: tomorrow morning I will look.
I agree you than maintain this here is the best but I had some questions
which are no related to this and I am sure you could answer them.

**Comment by cualquiercosa327** [comment]
No, it has no the cache dir.
I agree you than maintain this here is the best but I had some questions
which are no related to this and I am sure you could answer them.

**Comment by htmlbanjo** [comment]
Closing as stale until anyone reports specific translation issues.

**Comment by htmlbanjo** [comment]
Jamais Vu support currently in an RC on the 1.0-beta4RC1 branch.
